//! The factor handles `Ldlt`, `Lu`, `Klu`: one generic `Pair` (solver plus
//! the matrix it factored) over the `Direct` trait the three core solvers
//! share, wrapped per scalar field in an enum; the Python classes are
//! generated by the `handle!` macro so every method exists exactly once.

use std::marker::PhantomData;

use numpy::Element;
use pyo3::prelude::*;
use rslab::{
    BackwardError, CscMatrix, Diagnostics, GeneralCsc, KluSolver, LdltSolver, LinearOperator,
    LuSolver, Preconditioner, Recycle, RecycleScalar, RefineOutcome, RefinePolicy, RslabError,
    Scalar,
};

use crate::common::{
    array1, array2_row_major, block_row_major, diagnostics_dict, map_err, vector, Pattern, C32, C64,
};
use crate::krylov::{self, Operator};

// ---------------------------------------------------------------------------
// Scalar fields
// ---------------------------------------------------------------------------

/// A deflation-subspace carrier for :meth:`Ldlt.gmres` / :meth:`Lu.gmres` /
/// :meth:`Klu.gmres` sweeps, created by ``handle.recycle(k)``.
///
/// Holds up to ``k`` recycle vectors across calls (harvested Ritz vectors of
/// the preconditioned operator), so a sequence of related solves converges in
/// fewer iterations than cold or warm starts.
///
/// Attributes
/// ----------
/// k : int
///     Target subspace dimension.
/// active : int
///     Vectors currently held.
/// dtype : str
///     Scalar field, matching the handle that created it.
#[pyclass(name = "Recycle", module = "rslab")]
pub struct PyRecycle {
    pub inner: std::cell::RefCell<RecycleAny>,
}

pub enum RecycleAny {
    F64(Recycle<f64>),
    F32(Recycle<f32>),
    C64(Recycle<C64>),
    C32(Recycle<C32>),
}

#[pymethods]
impl PyRecycle {
    #[getter]
    fn k(&self) -> usize {
        match &*self.inner.borrow() {
            RecycleAny::F64(r) => r.dim(),
            RecycleAny::F32(r) => r.dim(),
            RecycleAny::C64(r) => r.dim(),
            RecycleAny::C32(r) => r.dim(),
        }
    }

    #[getter]
    fn active(&self) -> usize {
        match &*self.inner.borrow() {
            RecycleAny::F64(r) => r.active(),
            RecycleAny::F32(r) => r.active(),
            RecycleAny::C64(r) => r.active(),
            RecycleAny::C32(r) => r.active(),
        }
    }

    #[getter]
    fn dtype(&self) -> &'static str {
        match &*self.inner.borrow() {
            RecycleAny::F64(_) => f64::DTYPE,
            RecycleAny::F32(_) => f32::DTYPE,
            RecycleAny::C64(_) => C64::DTYPE,
            RecycleAny::C32(_) => C32::DTYPE,
        }
    }

    /// Drop the held vectors (the next solve starts cold).
    fn clear(&self) {
        match &mut *self.inner.borrow_mut() {
            RecycleAny::F64(r) => r.clear(),
            RecycleAny::F32(r) => r.clear(),
            RecycleAny::C64(r) => r.clear(),
            RecycleAny::C32(r) => r.clear(),
        }
    }

    fn __repr__(&self) -> String {
        format!(
            "Recycle(k={}, active={}, dtype='{}')",
            self.k(),
            self.active(),
            self.dtype()
        )
    }
}

/// One of the four scalar fields, with the glue that ties a concrete type to
/// the per-field enum variants.
pub trait Field: Scalar + Element + RecycleScalar + Default + Send + Sync + 'static {
    const DTYPE: &'static str;
    fn recycle_new(k: usize) -> RecycleAny;
    fn recycle_mut(any: &mut RecycleAny) -> Option<&mut Recycle<Self>>;
    fn ldlt(p: Pair<Self, LdltSolver<Self>>) -> LdltAny;
    fn lu(p: Pair<Self, LuSolver<Self>>) -> LuAny;
    fn klu(p: Pair<Self, KluSolver<Self>>) -> KluAny;
}

macro_rules! field {
    ($T:ty, $name:literal, $variant:ident) => {
        impl Field for $T {
            const DTYPE: &'static str = $name;
            fn recycle_new(k: usize) -> RecycleAny {
                RecycleAny::$variant(Recycle::new(k))
            }
            fn recycle_mut(any: &mut RecycleAny) -> Option<&mut Recycle<Self>> {
                match any {
                    RecycleAny::$variant(r) => Some(r),
                    _ => None,
                }
            }
            fn ldlt(p: Pair<Self, LdltSolver<Self>>) -> LdltAny {
                LdltAny::$variant(p)
            }
            fn lu(p: Pair<Self, LuSolver<Self>>) -> LuAny {
                LuAny::$variant(p)
            }
            fn klu(p: Pair<Self, KluSolver<Self>>) -> KluAny {
                KluAny::$variant(p)
            }
        }
    };
}
field!(f64, "float64", F64);
field!(f32, "float32", F32);
field!(C64, "complex128", C64);
field!(C32, "complex64", C32);

// ---------------------------------------------------------------------------
// The direct-solver interface the three core solvers share
// ---------------------------------------------------------------------------

pub trait Direct<T: Field>: Preconditioner<T> + Send + Sync + Sized {
    type Matrix: LinearOperator<T> + Send + Sync;
    fn n(&self) -> usize;
    fn factor_nnz(&self) -> usize;
    fn n_perturbed(&self) -> usize;
    fn diagnostics(&self) -> Diagnostics;
    fn solve(&self, b: &[T]) -> Result<Vec<T>, RslabError>;
    fn solve_many(&self, b: &[T], nrhs: usize) -> Result<Vec<T>, RslabError>;
    fn solve_refined_with(
        &self,
        a: &Self::Matrix,
        b: &[T],
        policy: &RefinePolicy,
    ) -> Result<(Vec<T>, RefineOutcome), RslabError>;
}

macro_rules! direct {
    ($solver:ident, $matrix:ident, |$s:ident| $n_perturbed:expr) => {
        impl<T: Field> Direct<T> for $solver<T> {
            type Matrix = $matrix<T>;
            fn n(&self) -> usize {
                $solver::n(self)
            }
            fn factor_nnz(&self) -> usize {
                $solver::factor_nnz(self)
            }
            fn n_perturbed(&self) -> usize {
                let $s = self;
                $n_perturbed
            }
            fn diagnostics(&self) -> Diagnostics {
                $solver::diagnostics(self)
            }
            fn solve(&self, b: &[T]) -> Result<Vec<T>, RslabError> {
                $solver::solve(self, b)
            }
            fn solve_many(&self, b: &[T], nrhs: usize) -> Result<Vec<T>, RslabError> {
                $solver::solve_many(self, b, nrhs)
            }
            fn solve_refined_with(
                &self,
                a: &Self::Matrix,
                b: &[T],
                policy: &RefinePolicy,
            ) -> Result<(Vec<T>, RefineOutcome), RslabError> {
                $solver::solve_refined_with(self, a, b, policy)
            }
        }
    };
}
direct!(LdltSolver, CscMatrix, |s| LdltSolver::n_perturbed(s));
direct!(LuSolver, GeneralCsc, |s| LuSolver::n_perturbed(s));
// The KLU path never perturbs a pivot (structural zero-free diagonal + threshold pivoting).
direct!(KluSolver, GeneralCsc, |_s| 0);

/// A factor together with the matrix it was computed from (kept for iterative
/// refinement and as the default Krylov operator).
pub struct Pair<T: Field, S: Direct<T>> {
    pub s: S,
    pub a: S::Matrix,
    _t: PhantomData<T>,
}

pub fn refine_policy(refine: usize, target: Option<f64>, measure: &str) -> PyResult<RefinePolicy> {
    let measure = match measure {
        "normwise" => BackwardError::Normwise,
        "componentwise" => BackwardError::Componentwise,
        other => {
            return Err(pyo3::exceptions::PyValueError::new_err(format!(
                "measure must be 'normwise' or 'componentwise', got '{other}'"
            )))
        }
    };
    Ok(RefinePolicy {
        max_steps: refine,
        target: target.unwrap_or(0.0),
        measure,
    })
}

impl<T: Field, S: Direct<T>> Pair<T, S> {
    pub fn new(s: S, a: S::Matrix) -> Self {
        Self {
            s,
            a,
            _t: PhantomData,
        }
    }

    pub fn diagnostics(&self, py: Python<'_>) -> PyResult<PyObject> {
        diagnostics_dict(py, &self.s.diagnostics())
    }

    pub fn solve(
        &self,
        py: Python<'_>,
        b: &Bound<'_, PyAny>,
        refine: usize,
        target: Option<f64>,
        measure: &str,
    ) -> PyResult<PyObject> {
        let bvec = vector::<T>(b, "rhs")?;
        let policy = refine_policy(refine, target, measure)?;
        let x = py
            .allow_threads(|| {
                if policy.max_steps > 0 {
                    self.s
                        .solve_refined_with(&self.a, &bvec, &policy)
                        .map(|(x, _)| x)
                } else {
                    self.s.solve(&bvec)
                }
            })
            .map_err(map_err)?;
        Ok(array1(py, x))
    }

    pub fn solve_many(&self, py: Python<'_>, b: &Bound<'_, PyAny>) -> PyResult<PyObject> {
        // The core's batched solve works on the row-major `n x nrhs` layout
        // NumPy hands over, so no transposition on either side.
        let (n, nrhs, rm) = block_row_major::<T>(b, "rhs")?;
        let x = py
            .allow_threads(|| self.s.solve_many(&rm, nrhs))
            .map_err(map_err)?;
        array2_row_major(py, x, n, nrhs)
    }

    /// The Krylov operator: the factored matrix, or an explicit override.
    fn operator(&self, operator: Option<Operator<'_>>) -> PyResult<Option<GeneralCsc<T>>> {
        match operator {
            None => Ok(None),
            Some((n, indptr, indices, data)) => {
                let pat = Pattern::from_py(n, &indptr, &indices)?;
                Ok(Some(pat.general(vector::<T>(&data, "operator data")?)?))
            }
        }
    }

    #[allow(clippy::too_many_arguments)]
    pub fn gmres(
        &self,
        py: Python<'_>,
        b: &Bound<'_, PyAny>,
        tol: f64,
        maxit: usize,
        restart: Option<usize>,
        x0: Option<&Bound<'_, PyAny>>,
        recycle: Option<&Bound<'_, PyRecycle>>,
        operator: Option<Operator<'_>>,
    ) -> PyResult<PyObject> {
        let ext = self.operator(operator)?;
        let op: &(dyn LinearOperator<T> + Sync) = match &ext {
            Some(g) => g,
            None => &self.a,
        };
        krylov::gmres(py, op, &self.s, b, tol, maxit, restart, x0, recycle)
    }

    #[allow(clippy::too_many_arguments)]
    pub fn gmres_block(
        &self,
        py: Python<'_>,
        b: &Bound<'_, PyAny>,
        tol: f64,
        maxit: usize,
        restart: Option<usize>,
        x0: Option<&Bound<'_, PyAny>>,
        operator: Option<Operator<'_>>,
    ) -> PyResult<PyObject> {
        let ext = self.operator(operator)?;
        let op: &(dyn LinearOperator<T> + Sync) = match &ext {
            Some(g) => g,
            None => &self.a,
        };
        krylov::gmres_block(py, op, &self.s, b, tol, maxit, restart, x0)
    }

    pub fn cocg(
        &self,
        py: Python<'_>,
        b: &Bound<'_, PyAny>,
        tol: f64,
        maxit: usize,
        operator: Option<Operator<'_>>,
    ) -> PyResult<PyObject> {
        let ext = self.operator(operator)?;
        let op: &(dyn LinearOperator<T> + Sync) = match &ext {
            Some(g) => g,
            None => &self.a,
        };
        krylov::cocg(py, op, &self.s, b, tol, maxit)
    }

    pub fn cocr(
        &self,
        py: Python<'_>,
        b: &Bound<'_, PyAny>,
        tol: f64,
        maxit: usize,
        operator: Option<Operator<'_>>,
    ) -> PyResult<PyObject> {
        let ext = self.operator(operator)?;
        let op: &(dyn LinearOperator<T> + Sync) = match &ext {
            Some(g) => g,
            None => &self.a,
        };
        krylov::cocr(py, op, &self.s, b, tol, maxit)
    }

    pub fn recycle(&self, k: usize) -> PyRecycle {
        PyRecycle {
            inner: std::cell::RefCell::new(T::recycle_new(k)),
        }
    }
}

impl<T: Field> Pair<T, LdltSolver<T>> {
    pub fn inertia(&self) -> (usize, usize, usize) {
        let i = self.s.inertia();
        (i.positive, i.negative, i.zero)
    }
}

impl<T: Field> Pair<T, KluSolver<T>> {
    pub fn solve_transpose(&self, py: Python<'_>, b: &Bound<'_, PyAny>) -> PyResult<PyObject> {
        let bvec = vector::<T>(b, "rhs")?;
        let x = py
            .allow_threads(|| self.s.solve_transpose(&bvec))
            .map_err(map_err)?;
        Ok(array1(py, x))
    }

    pub fn refactor(&mut self, py: Python<'_>, data: &Bound<'_, PyAny>) -> PyResult<()> {
        let pattern = crate::common::Pattern {
            n: self.a.n,
            col_ptr: self.a.col_ptr.clone(),
            row_idx: self.a.row_idx.clone(),
        };
        let data = &pattern.values_of(py, data, false)?;
        let d = vector::<T>(data, "data")?;
        if d.len() != self.a.values.len() {
            return Err(pyo3::exceptions::PyValueError::new_err(format!(
                "data length {} does not match the factored pattern nnz {}",
                d.len(),
                self.a.values.len()
            )));
        }
        self.a.values.copy_from_slice(&d);
        let (s, a) = (&mut self.s, &self.a);
        py.allow_threads(|| s.refactor(a)).map_err(map_err)
    }
}

// ---------------------------------------------------------------------------
// The Python classes
// ---------------------------------------------------------------------------

/// Run `$body` with `$p` bound to the typed `Pair` inside a per-field enum.
macro_rules! dispatch {
    ($any:ident, $inner:expr, |$p:ident| $body:expr) => {
        match $inner {
            $any::F64($p) => $body,
            $any::F32($p) => $body,
            $any::C64($p) => $body,
            $any::C32($p) => $body,
        }
    };
}

macro_rules! handle {
    (
        $(#[$meta:meta])*
        $name:ident, $any:ident, $solver:ident;
        $($extra:tt)*
    ) => {
        pub enum $any {
            F64(Pair<f64, $solver<f64>>),
            F32(Pair<f32, $solver<f32>>),
            C64(Pair<C64, $solver<C64>>),
            C32(Pair<C32, $solver<C32>>),
        }

        $(#[$meta])*
        #[pyclass(module = "rslab")]
        pub struct $name {
            pub inner: $any,
        }

        #[pymethods]
        impl $name {
            /// Matrix dimension ``n``.
            #[getter]
            fn n(&self) -> usize {
                dispatch!($any, &self.inner, |p| p.s.n())
            }

            /// Stored factor entries (the fill).
            #[getter]
            fn factor_nnz(&self) -> usize {
                dispatch!($any, &self.inner, |p| p.s.factor_nnz())
            }

            /// Statically perturbed pivots (nonzero only in preconditioner mode).
            #[getter]
            fn n_perturbed(&self) -> usize {
                dispatch!($any, &self.inner, |p| p.s.n_perturbed())
            }

            /// NumPy dtype name of the factor (``'float64'``, ``'float32'``,
            /// ``'complex128'`` or ``'complex64'``).
            #[getter]
            fn dtype(&self) -> &'static str {
                match &self.inner {
                    $any::F64(_) => f64::DTYPE,
                    $any::F32(_) => f32::DTYPE,
                    $any::C64(_) => C64::DTYPE,
                    $any::C32(_) => C32::DTYPE,
                }
            }

            /// The factorization report as a dictionary: ``stages`` (name,
            /// wall_ms, flops, bytes per phase), ``decisions`` (ordering,
            /// scaling, method, supernode counts), ``numeric`` (perturbed
            /// pivots, 2x2 pivots, inertia), ``solves`` (accumulated solve
            /// calls, right-hand sides, wall time, refinement steps),
            /// ``warnings`` (settings that were ignored on this path), the
            /// throughput ``rates`` (``analyze_mdof_s``, ``factor_mdof_s``,
            /// ``factor_gflops``, ``factor_mnnz_s``, ``total_mdof_s``,
            /// ``solve_mdof_s``; million unknowns per second and GFlop/s),
            /// the a-priori ``estimate`` and a one-line ``summary``.
            fn diagnostics(&self, py: Python<'_>) -> PyResult<PyObject> {
                dispatch!($any, &self.inner, |p| p.diagnostics(py))
            }

            /// Solve ``A x = b`` for one right-hand side.
            ///
            /// Parameters
            /// ----------
            /// b : ndarray, shape (n,)
            ///     Right-hand side in the factor's dtype.
            /// refine : int, default 0
            ///     Steps of iterative refinement against the original matrix.
            /// target : float, optional
            ///     Stop refining once the backward error is below this value
            ///     (by default all ``refine`` steps run).
            /// measure : {'normwise', 'componentwise'}, default 'normwise'
            ///     The backward-error measure ``target`` refers to.
            #[pyo3(signature = (b, refine = 0, target = None, measure = "normwise"))]
            fn solve(
                &self,
                py: Python<'_>,
                b: &Bound<'_, PyAny>,
                refine: usize,
                target: Option<f64>,
                measure: &str,
            ) -> PyResult<PyObject> {
                dispatch!($any, &self.inner, |p| p.solve(py, b, refine, target, measure))
            }

            /// Solve ``A X = B`` for an ``n x nrhs`` block in one batched pass.
            ///
            /// Parameters
            /// ----------
            /// b : ndarray, shape (n, nrhs)
            ///     Right-hand side block in the factor's dtype.
            ///
            /// Returns
            /// -------
            /// ndarray, shape (n, nrhs)
            ///     The solutions, one column per right-hand side.
            fn solve_many(&self, py: Python<'_>, b: &Bound<'_, PyAny>) -> PyResult<PyObject> {
                dispatch!($any, &self.inner, |p| p.solve_many(py, b))
            }

            /// Flexible restarted GMRES with this factor as the preconditioner.
            ///
            /// Parameters
            /// ----------
            /// b : ndarray, shape (n,)
            ///     Right-hand side.
            /// tol : float, default 1e-8
            ///     Relative residual target ``||b - A x|| <= tol * ||b||``.
            /// maxit : int, default 400
            ///     Iteration budget.
            /// restart : int, optional
            ///     Arnoldi basis size; by default chosen so the basis stays
            ///     under 1 GiB (between 20 and 80).
            /// x0 : ndarray, optional
            ///     Initial guess (warm start).
            /// recycle : Recycle, optional
            ///     Deflation subspace carried across calls; see :meth:`recycle`.
            /// operator : tuple, optional
            ///     ``(n, indptr, indices, data)`` of a different CSC matrix to
            ///     iterate on, with this factor as the preconditioner (the
            ///     Python wrapper :func:`rslab.gmres` builds it from a SciPy
            ///     matrix). By default the factored matrix is the operator.
            ///
            /// Returns
            /// -------
            /// KrylovResult
            ///     ``x``, ``converged``, ``iters``, ``final_res``, ``stop``;
            ///     unpacks as a 5-tuple.
            #[pyo3(signature = (b, tol = 1e-8, maxit = 400, restart = None, x0 = None, recycle = None, operator = None))]
            #[allow(clippy::too_many_arguments)]
            fn gmres(
                &self,
                py: Python<'_>,
                b: &Bound<'_, PyAny>,
                tol: f64,
                maxit: usize,
                restart: Option<usize>,
                x0: Option<Bound<'_, PyAny>>,
                recycle: Option<Bound<'_, PyRecycle>>,
                operator: Option<Operator<'_>>,
            ) -> PyResult<PyObject> {
                dispatch!($any, &self.inner, |p| p.gmres(
                    py, b, tol, maxit, restart, x0.as_ref(), recycle.as_ref(), operator
                ))
            }

            /// Block GMRES for an ``n x nrhs`` right-hand side block with this
            /// factor as the preconditioner.
            ///
            /// Parameters
            /// ----------
            /// b : ndarray, shape (n, nrhs)
            ///     Right-hand side block.
            /// tol : float, default 1e-8
            ///     Relative residual target per column.
            /// maxit : int, default 400
            ///     Iteration budget.
            /// restart : int, optional
            ///     Block Arnoldi basis size (see :meth:`gmres`).
            /// x0 : ndarray, shape (n, nrhs), optional
            ///     Initial guess.
            /// operator : tuple, optional
            ///     A different CSC matrix to iterate on, as in :meth:`gmres`.
            ///
            /// Returns
            /// -------
            /// KrylovResult
            ///     ``x`` of shape ``(n, nrhs)``, ``converged``, ``iters``,
            ///     ``final_res`` (one value per column), ``stop``.
            #[pyo3(signature = (b, tol = 1e-8, maxit = 400, restart = None, x0 = None, operator = None))]
            #[allow(clippy::too_many_arguments)]
            fn gmres_block(
                &self,
                py: Python<'_>,
                b: &Bound<'_, PyAny>,
                tol: f64,
                maxit: usize,
                restart: Option<usize>,
                x0: Option<Bound<'_, PyAny>>,
                operator: Option<Operator<'_>>,
            ) -> PyResult<PyObject> {
                dispatch!($any, &self.inner, |p| p.gmres_block(
                    py, b, tol, maxit, restart, x0.as_ref(), operator
                ))
            }

            /// Conjugate orthogonal conjugate gradient (COCG) with this factor
            /// as the preconditioner: the short-recurrence method for
            /// complex-symmetric (``A = A^T``) and real symmetric operators.
            ///
            /// Parameters
            /// ----------
            /// b : ndarray, shape (n,)
            ///     Right-hand side.
            /// tol : float, default 1e-8
            ///     Relative residual target.
            /// maxit : int, default 400
            ///     Iteration budget.
            /// operator : tuple, optional
            ///     A different CSC matrix to iterate on, as in :meth:`gmres`.
            ///
            /// Returns
            /// -------
            /// KrylovResult
            ///     ``x``, ``converged``, ``iters``, ``final_res``, ``stop``.
            #[pyo3(signature = (b, tol = 1e-8, maxit = 400, operator = None))]
            fn cocg(
                &self,
                py: Python<'_>,
                b: &Bound<'_, PyAny>,
                tol: f64,
                maxit: usize,
                operator: Option<Operator<'_>>,
            ) -> PyResult<PyObject> {
                dispatch!($any, &self.inner, |p| p.cocg(py, b, tol, maxit, operator))
            }

            /// Conjugate orthogonal conjugate residual (COCR) with this factor
            /// as the preconditioner; the minimal-residual sibling of
            /// :meth:`cocg` for complex-symmetric operators.
            ///
            /// Parameters
            /// ----------
            /// b : ndarray, shape (n,)
            ///     Right-hand side.
            /// tol : float, default 1e-8
            ///     Relative residual target.
            /// maxit : int, default 400
            ///     Iteration budget.
            /// operator : tuple, optional
            ///     A different CSC matrix to iterate on, as in :meth:`gmres`.
            ///
            /// Returns
            /// -------
            /// KrylovResult
            ///     ``x``, ``converged``, ``iters``, ``final_res``, ``stop``.
            #[pyo3(signature = (b, tol = 1e-8, maxit = 400, operator = None))]
            fn cocr(
                &self,
                py: Python<'_>,
                b: &Bound<'_, PyAny>,
                tol: f64,
                maxit: usize,
                operator: Option<Operator<'_>>,
            ) -> PyResult<PyObject> {
                dispatch!($any, &self.inner, |p| p.cocr(py, b, tol, maxit, operator))
            }

            /// A :class:`Recycle` workspace holding up to ``k`` deflation
            /// vectors for a sequence of :meth:`gmres` calls.
            ///
            /// Parameters
            /// ----------
            /// k : int
            ///     Maximum number of deflation vectors kept.
            ///
            /// Returns
            /// -------
            /// Recycle
            ///     The workspace to pass as ``recycle=`` to :meth:`gmres`.
            fn recycle(&self, k: usize) -> PyRecycle {
                dispatch!($any, &self.inner, |p| p.recycle(k))
            }

            $($extra)*
        }
    };
}

handle! {
    /// A symmetric factor ``P^T A P = L D L^T`` (Bunch-Kaufman), from
    /// :func:`rslab.ldlt` or :meth:`LdltSymbolic.factor`.
    ///
    /// Holds the supernodal factor, the permutation, the equilibration and a
    /// copy of the original lower triangle (for refinement and as the default
    /// Krylov operator), so the factorization is paid once and amortized over
    /// many solves.
    Ldlt, LdltAny, LdltSolver;

    /// Inertia ``(n_pos, n_neg, n_zero)``: the eigenvalue sign counts of ``A``
    /// read off ``D`` (Sylvester's law).
    #[getter]
    fn inertia(&self) -> (usize, usize, usize) {
        dispatch!(LdltAny, &self.inner, |p| p.inertia())
    }

    fn __repr__(&self) -> String {
        format!("Ldlt(n={}, factor_nnz={}, dtype='{}')", self.n(), self.factor_nnz(), self.dtype())
    }
}

handle! {
    /// A general (unsymmetric) factor ``P_r^T A P_c = L U`` (supernodal
    /// left-looking or multifrontal LU with threshold pivoting), from
    /// :func:`rslab.lu` or :meth:`LuSymbolic.factor`.
    Lu, LuAny, LuSolver;

    fn __repr__(&self) -> String {
        format!("Lu(n={}, factor_nnz={}, dtype='{}')", self.n(), self.factor_nnz(), self.dtype())
    }
}

handle! {
    /// A KLU-path factor (block triangular form plus per-block Gilbert-Peierls
    /// LU) for circuit-shaped matrices, from :func:`rslab.klu` or
    /// :meth:`KluSymbolic.factor`. Supports the numeric-only :meth:`refactor`
    /// for fixed-pattern sweeps and :meth:`solve_transpose`.
    Klu, KluAny, KluSolver;

    /// Number of diagonal blocks of the block triangular form.
    #[getter]
    fn n_blocks(&self) -> usize {
        dispatch!(KluAny, &self.inner, |p| p.s.n_blocks())
    }

    /// Solve ``A^T y = b`` on the same factors (plain transpose, not the
    /// conjugate transpose; conjugate the right-hand side and the result for
    /// ``A^H``).
    ///
    /// Parameters
    /// ----------
    /// b : ndarray, shape (n,)
    ///     Right-hand side in the factor's dtype.
    ///
    /// Returns
    /// -------
    /// ndarray, shape (n,)
    ///     The solution ``y``.
    fn solve_transpose(&self, py: Python<'_>, b: &Bound<'_, PyAny>) -> PyResult<PyObject> {
        dispatch!(KluAny, &self.inner, |p| p.solve_transpose(py, b))
    }

    /// Numeric-only refactorization with new values on the **same** pattern:
    /// no symbolic work, no pivot search. ``data`` is either the matrix
    /// itself (any SciPy sparse matrix with the factored pattern; it is
    /// sorted and summed like at analysis time, and the pattern is checked)
    /// or its CSC value array in the factor's dtype, in the order of the
    /// matrix that was factored.
    /// The handle is invalid until a successful ``refactor`` or a fresh
    /// factor if this raises.
    ///
    /// Parameters
    /// ----------
    /// data : scipy.sparse matrix or ndarray
    ///     The matrix with the factored pattern, or its CSC value array.
    ///
    /// Raises
    /// ------
    /// ValueError
    ///     If the pattern differs or the value count does not match.
    /// RuntimeError
    ///     If a pivot is numerically zero.
    fn refactor(&mut self, py: Python<'_>, data: &Bound<'_, PyAny>) -> PyResult<()> {
        dispatch!(KluAny, &mut self.inner, |p| p.refactor(py, data))
    }

    fn __repr__(&self) -> String {
        format!(
            "Klu(n={}, factor_nnz={}, n_blocks={}, dtype='{}')",
            self.n(), self.factor_nnz(), self.n_blocks(), self.dtype()
        )
    }
}
